#!/usr/bin/env python3
"""
make_font_icons_bin.py
Extracts array data from font5x7.h and icons.h into a flat binary file
and a text offset map for use with rp6502_asset() XRAM preloading.

Usage: python tools/make_font_icons_bin.py
Outputs: assets/font&icons.bin, assets/font&icons.txt
"""

import os
import re
import struct

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(SCRIPT_DIR)
SRC = os.path.join(ROOT, "src")
ASSETS = os.path.join(ROOT, "assets")

FONT_H   = os.path.join(SRC, "font5x7.h")
ICONS_H  = os.path.join(SRC, "icons.h")
OUT_BIN  = os.path.join(ASSETS, "font&icons.bin")
OUT_TXT  = os.path.join(ASSETS, "font&icons.txt")


def parse_literal(s):
    s = s.strip()
    if s.startswith("0b") or s.startswith("0B"):
        return int(s, 2)
    if s.startswith("0x") or s.startswith("0X"):
        return int(s, 16)
    return int(s)


def extract_array_body(text, start_pos):
    """Return the content between the first { and its matching } after start_pos."""
    depth = 0
    i = start_pos
    while i < len(text) and text[i] != '{':
        i += 1
    start = i
    while i < len(text):
        if text[i] == '{':
            depth += 1
        elif text[i] == '}':
            depth -= 1
            if depth == 0:
                return text[start + 1:i]
        i += 1
    raise ValueError("Unmatched brace starting at pos %d" % start_pos)


def extract_values(body):
    """Extract all numeric literals from an array body (handles nested {})."""
    # Remove comments
    body = re.sub(r'//[^\n]*', '', body)
    body = re.sub(r'/\*.*?\*/', '', body, flags=re.DOTALL)
    tokens = re.findall(r'0[bB][01]+|0[xX][0-9a-fA-F]+|[0-9]+', body)
    return [parse_literal(t) for t in tokens]


def read_file(path):
    with open(path, 'r', encoding='utf-8') as f:
        return f.read()


def strip_comments(text):
    """Remove // and /* */ comments."""
    text = re.sub(r'/\*.*?\*/', '', text, flags=re.DOTALL)
    text = re.sub(r'//[^\n]*', '', text)
    return text


def find_and_extract(text, name):
    """
    Find 'static const ... NAME[...] = {' and extract values.
    Returns list of ints or raises if not found.
    """
    pattern = re.compile(
        r'\bstatic\s+const\s+[\w\s]+?\s+' + re.escape(name) + r'\s*\[',
        re.DOTALL
    )
    m = pattern.search(text)
    if not m:
        raise ValueError("Array '%s' not found" % name)
    eq = text.index('=', m.end())
    body = extract_array_body(text, eq + 1)
    return extract_values(body)


def pack_uint8(values):
    return bytes(values)


def pack_uint16_le(values):
    return b''.join(struct.pack('<H', v) for v in values)


def main():
    font_src  = strip_comments(read_file(FONT_H))
    icons_src = strip_comments(read_file(ICONS_H))

    # ---- define extraction order and element type ----
    entries = []

    def add(name, src, etype):
        values = find_and_extract(src, name)
        if etype == 'uint8':
            data = pack_uint8(values)
        elif etype == 'uint16':
            data = pack_uint16_le(values)
        else:
            raise ValueError("Unknown type: " + etype)
        entries.append((name, data, etype, values))

    # font
    add('font',   font_src,  'uint8')   # 256*5 = 1280

    # 8bpp cursors
    add('arrow',     icons_src, 'uint8')  # 225
    add('cross',     icons_src, 'uint8')  # 225
    add('hourglass', icons_src, 'uint8')  # 225

    # 1bpp toolbar icons (uint16 LE)
    for name in [
        'erase_icon_black', 'erase_icon_white',
        'erase_icon_black_selected', 'erase_icon_white_selected',
        'swap_icon', 'save_icon',
        'invert_icon', 'invert_selected_icon',
        'select_icon', 'rect_tool_icon', 'ellipse_tool_icon',
        'mirrorV_tool_icon', 'mirrorH_tool_icon',
        'mirrorV_tool_selected_icon', 'mirrorH_tool_selected_icon',
    ]:
        add(name, icons_src, 'uint16')   # 16 * 2 = 32

    # shape brush icons 2D array
    add('icons', icons_src, 'uint8')    # 6*8 = 48

    # ---- build binary ----
    binary = b''
    map_lines = []
    map_lines.append('# font&icons binary map')
    map_lines.append('# generated by make_font_icons_bin.py')
    map_lines.append('# name                         offset   bytes  type    count')

    offset = 0
    for name, data, etype, values in entries:
        count = len(values)
        size  = len(data)
        map_lines.append(
            f'{name:<32} {offset:6d}  {size:5d}  {etype:<7} {count}'
        )
        binary += data
        offset += size

    map_lines.append(f'# TOTAL                        {offset:6d} bytes')

    os.makedirs(ASSETS, exist_ok=True)
    with open(OUT_BIN, 'wb') as f:
        f.write(binary)
    with open(OUT_TXT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(map_lines) + '\n')

    print(f"Written {OUT_BIN}  ({len(binary)} bytes)")
    print(f"Written {OUT_TXT}")
    print()
    print(open(OUT_TXT).read())


if __name__ == '__main__':
    main()
